### ISSUE TITLE
add to nuget

### ISSUE THREAD

**Issue by bbodenmiller** [cgarvis/angular-toggle-switch#20]
Similar to your Bower package would be great if you could add it to [NuGet](http://nuget.org).

**Comment by bbodenmiller** [comment]
Must be @ablaze8 and NuGet is still out of date. :(

**Comment by ablaze8** [comment]
neither me :-( I was trying the NuGet pilgrims to help. But I DO see a way to contact maintainers on the link below :+1:  https://www.nuget.org/users/account/LogOn?ReturnUrl=%2Fpackages%2Fangular-toggle-switch%2FContactOwners
