### ISSUE TITLE
Add Listener for changes

### ISSUE THREAD

**Issue by brycejacobs** [cgarvis/angular-toggle-switch#24]
Would it be possible to add a listener for when the user toggles? This would allow much easier coding when nesting the switch inside of lists.

**Comment by zhendong590** [comment]
i met this problem when i turn this switch ,the model doesn't change ,always false,$watch could not found it

**Comment by zhendong590** [comment]
i fix it ,cause i wrote `ng-if` on parentNote,i changed to `ng-show`,it works fine
