### ISSUE TITLE
Unable to switch the toggle

### ISSUE THREAD

**Issue by EgidioCaprino** [cgarvis/angular-toggle-switch#25]
Hi.

I'm unable to use this module. I get this error when I try to change the status of the switcher.

```
Error: [$compile:nonassign] Expression 'undefined' used with directive 'toggleSwitch' is non-assignable!
```

I included the **angular-toggle-switch.js** file and added the module to my app in this way.

``` javascript
var module = angular.module("app", ["ngRoute", "ngResource", "angularFileUpload", "ui.bootstrap", "ui.bootstrap.datetimepicker", "toggle-switch"]);
```

Where I'm wrong?

**Comment by zhendong590** [comment]
i met this problem when i turn this switch ,the model doesn't change ,however i use data-model or model,
$watch could not found it
