### ISSUE TITLE
"disabled" as boolean attribute

### ISSUE THREAD

**Issue by leesei** [cgarvis/angular-toggle-switch#52]
In HTML5, "disabled" as boolean attribute.
A input is disabled as long as "disabled" is defined in the attribute, regardless of its value.
http://www.w3.org/TR/html5/infrastructure.html#boolean-attribute

Can this logic handle the case
```html
<toggle-switch ng-model="switchStatus" disabled><toggle-switch>
```

```javascript
        attrs.$observe('disabled', function(disabled) {
          if(disabled === 'true') {
            isEnabled = false;
          } else {
            isEnabled = true;
          }
        });
```

**Comment by sgentile** [comment]
I fixed the issue with disabling in a fork: https://github.com/SMARTDATASYSTEMSLLC/angular-toggle-switch

**Comment by cgarvis** [comment]
In the latest release, this is how it works.
