### ISSUE TITLE
on true or false value

### ISSUE THREAD

**Issue by wesley3523** [cgarvis/angular-toggle-switch#57]
Is it possible to get other value than true or false? for example        
[ng-true-value=""]
[ng-false-value=""]

**Comment by cstephe** [comment]
quick example of how angular-material is doing this: https://material.angularjs.org/#/api/material.components.switch/directive/mdSwitch

**Comment by cgarvis** [comment]
Set a watch on your model and make set the values in your controller.

```javascript
$scope.watch('switchModel', function(val) {
  if(val) {
    $scope.otherValue = 'a';
  } else {
    $scope.othervalue = 'b';
  }
})
```
