### ISSUE TITLE
not needed console.log on code

### ISSUE THREAD

**Issue by tarlepp** [cgarvis/angular-toggle-switch#60]
https://github.com/cgarvis/angular-toggle-switch/blob/master/angular-toggle-switch.js#L71

**Comment by dasrick** [comment]
+1

**Comment by cgarvis** [comment]
Removed.  Thanks for finding that.

**Comment by tarlepp** [comment]
nice, thanks!

btw, you should use commit messages that is linked to actual issue, you can also close issues by that like: 'Removed not needed console.log, fixes #60'
