### ISSUE TITLE
Question: Is there a event handle on change in angular-toggle-switch?

### ISSUE THREAD

**Issue by peterhe2000** [cgarvis/angular-toggle-switch#61]
There was a event on-change in release 0.5.2? 
I could not get this happening in release 1.2.1?

**Comment by cgarvis** [comment]
Currently you use a watch on your model.

**Comment by peterhe2000** [comment]
Depending on the id the switch gives to a function I will change something. How do i watch multiple switches and react on there ids in my model? Thanks in advance.

**Comment by twalling** [comment]
I have a PR which adds support for ng-change.

**Comment by cgarvis** [comment]
ng-change has been added to in 1.3.0
