### ISSUE TITLE
ngMin causes problems with webpack or browserify

### ISSUE THREAD

**Issue by voor** [cgarvis/angular-toggle-switch#66]
Hi, the fact you're using ngMin creates an issue with packaging your directive and then running minification on the entire package instead of including the minified version.

**Comment by voor** [comment]
I was going to make a pull request, but #62 already satisfies this issue.

**Comment by cgarvis** [comment]
Yeah I was using this before webpack became so popular.  It's starting to look like me managing the minified version doesn't make sense.
