### ISSUE TITLE
Knob Label issue

### ISSUE THREAD

**Issue by mkamyszek** [cgarvis/angular-toggle-switch#68]
No knob label added, but one is added automatically:

HTML:
`<toggle-switch ng-model="stat.show"><toggle-switch>`

Inspector:
`<span class="knob ng-binding" ng-bind="knobLabel">Â&nbsp;</span>`

![2015-05-21_1654](https://cloud.githubusercontent.com/assets/1405412/7758766/15507136-ffda-11e4-8f12-60336dec8dc6.png)

**Comment by cgarvis** [comment]
what happens if you add `<meta charset='utf-8'>` to the top of your html file?

**Comment by mkamyszek** [comment]
Fixed, thanks!
